const list = [
    {
      id:1,
      name: "108 Panchatantra Stories",
      author: "Maple Press",
      image: "https://m.media-amazon.com/images/I/81VJ+MAc7YL._AC._SR360,460.jpg",
      price: 140,
      amount:1,
    },
    {   
        id:2,
        name: "The Illustrated Stories of Tenali Raman: Classic Tales From India ",
        author: "Wonder House books",
        image: "https://m.media-amazon.com/images/I/71tVvU10bzL._AC._SR360,460.jpg",
        price: 179,
        amount:1,
      },
      {
        id:3,
        name: "108 Moral Stories ",
        author: "Maple Press",
        image: "https://m.media-amazon.com/images/I/81y4kJnEzbL._AC._SR360,460.jpg",
        price: 134,
        amount:1,
      },
      {
        id:4,
        name: "Greatest Short Stories For Children",
        author: "Various",
        image: "https://m.media-amazon.com/images/I/71946HWMZYL._AC._SR360,460.jpg",
        price: 149,
        amount:1,
      },
      { 
        id:5,
        name: "The Girl With A Secret Crush",
        author: "Sudha Nair",
        image: "https://m.media-amazon.com/images/I/81CzpNZ9NuL._UX300_PJku-sticker-v8,TopRight,0,-50._AC._SR360,460_.jpg",
        price: 198,
        amount:1,
      },
      { 
        id:6,
        name: "Men without Women",
        author: " Haruki Murakami",
        image: "https://m.media-amazon.com/images/I/61jE8ravkbL._AC._SR360,460.jpg",
        price: 414,
        amount:1,
      },
      { 
        id:7,
        name: "Interpreter of Maladies: Stories of Bengal, Boston and Beyond",
        author: "Lahiri",
        image: "https://m.media-amazon.com/images/I/71EQ4i8Rq5L._AC._SR360,460.jpg",
        price: 323,
        amount:1,
      },
      { 
        id:8,
        name: "And They Survived",
        author: "Dr. Sapna Deb",
        image: "https://m.media-amazon.com/images/I/61xFxx8CezL._AC._SR360,460.jpg",
        price: 82,
        amount:1,
      },
      {
        id:9,
        name: "Princess Fairy Tales: Ten Traditional Fairy Tales For Children ",
        author: "Wonder House Books",
        image: "https://m.media-amazon.com/images/I/71TvY94ebeL._AC._SR360,460.jpg",
        price: 435,
        amount:1,
      },
      { 
        id:10,
        name: "METAMORPHORSIS",
        author: "franz kafka",
        image: "https://m.media-amazon.com/images/I/515qI4pCbHL._SY445_SX342_.jpg",
        price: 149,
        amount:1,
      },
      { 
        id:11,
        name: "KAALI",
        author: "Aswathy Shreekanth",
        image: "https://m.media-amazon.com/images/I/51cP2664iPL._SY522_.jpg",
        price: 132,
        amount:1,
      },
      { 
        id:12,
        name: "100 World’s Greatest Short Stories: Collectable Edition",
        author: "Various",
        image: "https://m.media-amazon.com/images/I/61CwmViXiYL._AC_UY327_FMwebp_QL65_.jpg",
        price: 239,
        amount:1,
      },
      { 
        id:13,
        name: "The Complete Sherlock Holmes ",
        author: "Arthur Conan Doyle",
        image: "https://m.media-amazon.com/images/I/51ZqLGyqiGL._SY445_SX342_.jpg",
        price: 86,
        amount:1,
      },
      
    ];
    export default list;
    

